#!/usr/bin/env bash

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/scripts"

## Java Fix
export _JAVA_AWT_WM_NONREPARENTING=1

## Configurations --------------------------------------------#

#Auto Workspace ---- Does not set monitor resolution and hertz
for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
	bspc monitor "$monitor" -d '1' '2' '3'
done

#laptop EXAMPLE
#  xrandr --output eDP-1 --primary --mode 2560x1600 --rate 60
#  bspc monitor -n eDP-1 -d '1' '2' '3'
#  bspc wm -O eDP-1

#Desktop EXAMPLE
#  xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rate 165 --output DisplayPort-2 --mode 1920x1080 ->
#  bspc wm -O HDMI-A-0 DisplayPort-2
#  bspc monitor HDMI-A-0 -d 1 2
#  bspc monitor DisplayPort-2 -d 1 2

## Apply bspwm configurations
bspc config border_width 3
bspc config window_gap 9
bspc config split_ratio 0.5

bspc config focused_border_color "#b4befe"
bspc config normal_border_color "#11111b"
bspc config active_border_color "#11111b"
bspc config presel_feedback_color "#ffffff"

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage unmanaged windows
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

bspc rule -r *:*
bspc rule -a Viewnior state=floating follow=on focus=on

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 sxhkd dunst ksuperkey polybar picom

picom &
sxhkd &
dunst &
autohide_polybar &

for mon in $(polybar --list-monitors | cut -d":" -f1); do
  MONITOR=$mon polybar -q main &
done

ksuperkey -e 'Super_L=Alt_L|F1'
ksuperkey -e 'Super_R=Alt_L|F1'

xsetroot -cursor_name left_ptr

nm-applet &

feh --bg-scale ~/.config/bspwm/wallpapers/cherry_blossom_lava.jpg
