#!/usr/bin/env bash

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/scripts"

## Java Fix
export _JAVA_AWT_WM_NONREPARENTING=1

## Configurations --------------------------------------------#


#bspc wm -O eDP-1 HDMI-1

#laptop
#xrandr --output eDP-1 --primary --mode 1920x1200 --rate 60 

#Desktop
xrandr --output HDMI-1 --primary --mode 1920x1080 --rate 165 --output DP-3 --mode 1920x1080 --right-of HDMI-1


## Do 'bspc query -M'

#Laptop
#bspc monitor -n eDP-1 -d '1' '2' '3'

#Desktop
bspc monitor HDMI-1 -d 1 2
bspc monitor DP-3 -d 1 2

## Apply bspwm configurations
bspc config border_width 3
bspc config window_gap 0
bspc config split_ratio 0.5

bspc config focused_border_color "#cba6f7"
bspc config normal_border_color "#11111b"
bspc config active_border_color "#11111b"
bspc config presel_feedback_color "#ffffff"

bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage unmanaged windows
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

bspc rule -r *:*
bspc rule -a discord-screenaudio desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^2' follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 sxhkd dunst ksuperkey bspc picom

# polkit agent

picom --config "$HOME"/.config/bspwm/picom.conf &
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
dunst -config "$HOME"/.config/bspwm/dunstrc &
bash "$HOME"/.config/bspwm/polybar/polybar.sh

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

xsetroot -cursor_name left_ptr

nm-applet &
