#!/usr/bin/env bash

sleep 3

BARHEIGHT=$((20))                          #polybar/config.ini ---- height
eval $(xdotool getdisplaygeometry --shell) #Pipes display width and height to $WIDTH and $HEIGHT

sleep 1

polybar-msg cmd hide
bspc config bottom_padding 0

while :; do
  sleep 0.25
  eval $(xdotool getmouselocation --shell)
  if [[ $((Y)) == $(($HEIGHT - 1)) ]]; then
    polybar-msg cmd show
    while [[ $((Y)) -ge $(($HEIGHT - $BARHEIGHT)) ]]; do
      sleep 0.15
      eval $(xdotool getmouselocation --shell)
    done
    polybar-msg cmd hide
    bspc config bottom_padding 0
  fi
done
