#!/usr/bin/env bash

notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obvolume'

# Get Volume
get_volume() {
	echo "`pulsemixer --get-volume | cut -d' ' -f1`"
}

# Notify
notify_user() {
	${notify_cmd} "Volume : $(get_volume)%"
}

# Increase Volume
inc_volume() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume +5 && notify_user
}

# Decrease Volume
dec_volume() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume -5 && notify_user
}

# Toggle Mute
toggle_mute() {
	if [[ `pulsemixer --get-mute` == 0 ]]; then
		pulsemixer --toggle-mute && ${notify_cmd} "Mute"
	else
		pulsemixer --toggle-mute && ${notify_cmd} "Unmute"
	fi
}

# Toggle Mic
toggle_mic() {
	ID="`pulsemixer --list-sources | grep 'Default' | cut -d',' -f1 | cut -d' ' -f3`"
	if [[ `pulsemixer --id $ID --get-mute` == 0 ]]; then
		pulsemixer --id ${ID} --toggle-mute && ${notify_cmd} "Microphone Switched OFF"
	else
		pulsemixer --id ${ID} --toggle-mute && ${notify_cmd} "Microphone Switched ON"
	fi
}

# Execute accordingly
if [[ -x `which pulsemixer` ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	elif [[ "$1" == "--toggle-mic" ]]; then
		toggle_mic
	else
		echo $(get_volume)%
	fi
else
	${notify_cmd} "'pulsemixer' is not installed."
fi
