#!/usr/bin/env bash

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="~/Pictures/Screenshots"
file="Screenshot_${time}.png"

if [[ ! -d "$dir" ]]; then
  mkdir -p "$dir"
fi

copy_shot() {
  tee "$file" | xclip -selection clipboard -t image/png
}

menu() {
  DIR="$HOME/.config/bspwm"
  RASI="$DIR/Purple.rasi"
  prompt='Klipper'
  mesg="Directory :: $(xdg-user-dir PICTURES)/Screenshots"

  layout=$(cat ${RASI} | cut -d'=' -f2)
  option_1="1 area"
  option_2="2 window"
  option_3="3 desktop"

  chosen="$(echo -e "$option_1\n$option_2\n$option_3" | rofi -dmenu -p "$prompt" -mesg "$mesg" -markup-rows)"
  case ${chosen} in
  $option_1)
    cd ${dir} && maim -u -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | copy_shot
    ;;
  $option_2)
    cd ${dir} && maim -u -f png -i $(xdotool getactivewindow) | copy_shot
    ;;
  $option_3)
    cd ${dir} && sleep 0.5 && maim -u -f png | copy_shot
    ;;
  esac
}

if [[ "$1" == "--now" ]]; then
  cd ${dir} && sleep 0.5 && maim -u -f png | copy_shot
elif [[ "$1" == "--win" ]]; then
  cd ${dir} && maim -u -f png -i $(xdotool getactivewindow) | copy_shot
elif [[ "$1" == "--area" ]]; then
  cd ${dir} && maim -u -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | copy_shot
elif [[ "$1" == "--menu" ]]; then
  menu
else
  echo -e "Available Options : --now --win --area --menu"
fi
