#!/usr/bin/env bash

prompt="Powermenu"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

layout=$(cat ${RASI} | cut -d'=' -f2)
option_1="1 lock"
option_2="2 logout"
option_3="3 suspend"
option_4="4 hibernate"
option_5="5 reboot"
option_6="6 shutdown"

yes='Yes'
no='No'

confirm_run() {
  selected="$(echo -e "$yes\n$no" | rofi -dmenu -p 'Confirmation' -mesg 'Are you Sure?')"
  if [[ "$selected" == "$yes" ]]; then
    ${1}
  else
    exit
  fi
}

chosen="$(echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi -dmenu -p "$prompt" -mesg "$mesg" -markup-rows)"

case ${chosen} in
$option_1)
  physlock
  ;;
$option_2)
  confirm_run 'bspc quit'
  ;;
$option_3)
  confirm_run 'systemctl suspend'
  ;;
$option_4)
  confirm_run 'systemctl hibernate'
  ;;
$option_5)
  confirm_run 'systemctl reboot'
  ;;
$option_6)
  confirm_run 'systemctl poweroff'
  ;;
esac
